### ISSUE TITLE
Uhm.........

### ISSUE THREAD

**Issue by mellowmarshe** [DisabledMallis/battles2cheat#2]
why is this not Rust:tm:

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
mark as answer

**Comment by mellowmarshe** [comment]
![FaL13OtUIAAVW4h](https://user-images.githubusercontent.com/35433518/185764929-28f5eb65-54c3-4290-ae00-f7dea9344dc6.png)

**Comment by ghost** [comment]
no chance this kids for REA:

**Comment by DisabledMallis** [comment]
It's written in C++ because C++ isn't a language made by renaming parts of C.

**Comment by ghost** [comment]
Okay, ASM. You think Rust isnt a real language but it infact is.

**Comment by DisabledMallis** [comment]
Rust is the most un-funny joke in programming history
